on:
  push

jobs:
  job1:
    env:
      x: 5
      y: 6
    runs-on: ubuntu-latest
    steps:
      - name: Display variable
        run:
          echo ${{env.x}}  
          echo ${{env.y}}
          echo ${{env.x}+{env.y}}
